[package]
name = "drs-primitives"
version = "0.1.0"
authors = ["Eugenio Tampieri <eugenio.tampieri@icloud.com>", "Michael Chelli"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
